version: "3"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URI: postgresql://postgres:postgres@db:5432/mydb
    command: ["python", "app.py"]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb

  test:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URI: postgresql://postgres:postgres@db:5432/mydb
    command: ["python", "-m", "unittest", "discover", "-s", "."]
